#!/usr/bin/env python3
"""
Convert a PNG file to a C header with a byte array, matching launcher_icon.h style.
Usage:
  ./png_to_c_array.py issuing_icon.png launcher_icon.h _launcher_icon_png
"""

from __future__ import annotations

import sys
from pathlib import Path

HEADER = """/*
 * Copyright (c) 2026.
 * SPDX-License-Identifier: Apache-2.0
 * Source: Generated by png_to_c_array.py.
 */
"""


def format_bytes(data: bytes, indent: str = "  ", per_line: int = 12) -> str:
    parts = [f"0x{b:02x}" for b in data]
    lines = []
    for i in range(0, len(parts), per_line):
        lines.append(indent + ", ".join(parts[i : i + per_line]) + ",")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 4:
        print("Usage: png_to_c_array.py <input.png> <output.h> <var_name>", file=sys.stderr)
        return 2

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    var_name = sys.argv[3]

    data = input_path.read_bytes()
    body = format_bytes(data)

    output = f"""{HEADER}
char {var_name}[] = {{
{body}
}};
"""

    output_path.write_text(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
