name: Publish iOS App
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 90
    steps:
      - name: Common setup
        uses: a-sit-plus/internal-workflows/.github/actions/common-setup@feature/modularTests
      - name: Prepare files from secrets
        run: |
          echo "${{ secrets.APPLE_CERT_CONTENT }}" > iosApp/cert.b64
          base64 -d -i iosApp/cert.b64 > iosApp/cert.p12
      - name: Upload to testflight
        run: fastlane deploy
        working-directory: iosApp
        env:
          FASTLANE_OPT_OUT_USAGE: true
          FASTLANE_XCODE_LIST_TIMEOUT: 120
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
          APPLE_API_KEY_CONTENT: ${{ secrets.APPLE_API_KEY_CONTENT }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          CI: true
      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: xcode.log
          path: "/Users/runner/Library/Logs/gym/Valera-iosApp.log"
